package exception;

public class Test43 {
	public static void main(String[] args)  
	{
	//	methodA();   throw exception required in main method
	}

	public static void methodA() throws Exception
	{
		System.out.println("Completed..");
	}

}
