package exception;

public class Test44 {
	
	public static void main(String[] args) throws Exception 
	{
		methodA();
	}

	public static void methodA() throws Exception
	{
		System.out.println("Completed..");
	}

}
